### ISSUE TITLE
Unable to connect with private key certificates

### ISSUE THREAD

**Issue by sensboston** [FarGroup/Far-NetBox#36] opened 2023-04-05 02:21 UTC
NetBox (latest release from here) can't connect to Ubuntu on OracleCloud using private key certificate (converted by PuTTY).
It's starts connecting, something like "Authorizing" quickly blinks on message dialog and plugin falls back to the session menu.

Standard Windows **sftp** program and **WinSCP** are working fine so it's a 100% NetBox plugin bug.
Could you please fix?

P.S. If you need a log or some additional information, please describe how to get it. BTW, it looks like not specific issue but outdated code base.

**Comment by asuiu** [comment] 2023-06-26 22:01
The problem is described here:
https://forum.farmanager.com/viewtopic.php?t=13048

The issue was solved in WinSCP 5.20 ([here](https://winscp.net/tracker/1952))
Thus the Netbox is just to be updated to use WinSCP 5.20

**Comment by achernyakevich-sc** [comment] 2023-06-27 06:34
> Thus the Netbox is just to be updated to use WinSCP 5.20

I have found issue in the author's (?) repository and added [summary](https://github.com/michaellukashov/Far-NetBox/issues/323#issuecomment-1567536056) there.

Author responded that he works on upgrading NetBox to use source code of newer version of WinSCP that already had fixed this issue.

**Comment by asuiu** [comment] 2023-06-27 07:24
The best is to migrate to more secure public cryptography algorithm like `ed25519`, which solves the problem.

**Comment by SergeAx** [comment] 2023-10-12 15:52
> Thus, the Netbox is just to be updated to use WinSCP 5.20

@asuiu , any suggestion where that may happen? I have a problem with ppk v3, which is also addressed in WnSCP 5.19+

**Comment by alabuzhev** [comment] 2024-02-22 21:45
Moved to https://github.com/michaellukashov/Far-NetBox/issues/392

**Closed by alabuzhev** 2024-02-22 21:45 UTC
